name: Build and Test Pull Requests

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: "Build and Test Pull Requests"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
        
    - name: Restore Nuget Packages
      run: dotnet restore EstateManagement.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Build Code
      run: dotnet build EstateManagement.sln --configuration Release

    - name: Run Unit Tests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        dotnet test "EstateManagement.BusinessLogic.Tests\EstateManagement.BusinessLogic.Tests.csproj"
        dotnet test "EstateManagement.ContractAggregate.Tests\EstateManagement.ContractAggregate.Tests.csproj"
        dotnet test "EstateManagement.EstateAggregate.Tests\EstateManagement.EstateAggregate.Tests.csproj"
        dotnet test "EstateManagement.MerchantAggregate.Tests\EstateManagement.MerchantAggregate.Tests.csproj"
        dotnet test "EstateManagement.MerchantDepositListAggregate.Tests\EstateManagement.MerchantDepositListAggregate.Tests.csproj"
        dotnet test "EstateManagement.MerchantStatementAggregate.Tests\EstateManagement.MerchantStatementAggregate.Tests.csproj"
        dotnet test "EstateManagement.Tests\EstateManagement.Tests.csproj"
        #dotnet test "EstateManagement.Repository.Tests\EstateManagement.Repository.Tests.csproj"        

    - name: Build Docker Image
      run: docker build . --file EstateManagement/Dockerfile --tag estatemanagement:latest
      
    - name: Run Integration Tests
      run: dotnet test "EstateManagement.IntegrationTests\EstateManagement.IntegrationTests.csproj" --filter Category=PRTest

    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: tracelogs
        path: /home/txnproc/trace/   